{{-- 
    Example: How to add SEO meta tags to your layout
    Add this to your main layout file (e.g., resources/views/layouts/app.blade.php)
--}}

<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    {{-- SEO Meta Tags - Generated by artesaos/seotools --}}
    {!! SEO::generate() !!}

    {{-- Or use individually: --}}
    {{-- {!! SEOMeta::generate() !!} --}}
    {{-- {!! OpenGraph::generate() !!} --}}
    {{-- {!! TwitterCard::generate() !!} --}}
    {{-- {!! JsonLd::generate() !!} --}}

    {{-- Canonical URL (if not using SEOTools) --}}
    @if(!isset($usesSEOTools))
        <link rel="canonical" href="{{ url()->current() }}" />
    @endif

    {{-- Favicon --}}
    <link rel="icon" type="image/png" href="{{ asset('favicon.png') }}">

    {{-- Fonts --}}
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

    {{-- Styles --}}
    @vite(['resources/css/app.css', 'resources/js/app.js'])

    {{-- Additional head content --}}
    @stack('head')
</head>
<body>
    {{-- JSON-LD Structured Data (if provided) --}}
    @if(isset($structuredData))
        <script type="application/ld+json">
            {!! json_encode($structuredData, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT) !!}
        </script>
    @endif

    {{-- Page Content --}}
    <div id="app">
        @yield('content')
    </div>

    {{-- Scripts --}}
    @stack('scripts')
</body>
</html>
